### ISSUE TITLE
"Average Layer Time" shows only a value (in seconds?) after update

### ISSUE THREAD

**Issue by energiebrand** [StefanCohen/OctoPrint-Dashboard#130] opened 2020-03-05 10:53 UTC
Yesterday 5th of March 2020 updated the plugin to the latest version. After this during all prints instead of showing hours/minutes/seconds it just shows a value (maybe seconds). 
Version is Octoprint 1.3.12 on OctoPi 0.17.0 (Raspberry Pi 3B+).
I did a reset (did not change any value before) but no change.

Maybe also Estimated total print time does not work anymore....

![version](https://user-images.githubusercontent.com/60507600/75974751-9fc9bf00-5ed7-11ea-8a2f-c449b89099cc.jpg)
![Value](https://user-images.githubusercontent.com/60507600/75974760-a22c1900-5ed7-11ea-88cf-84d5aad8cc68.jpg)

**Comment by StefanCohen** [comment] 2020-03-05 11:05
Thanks. I see what the problem is and will provide a fix.

**Comment by energiebrand** [comment] 2020-03-05 16:12
Started a print on a different printer with another Octoprint server RPI 3B on Octoprint 1.4.0 on Octpi 0.16.0 with a different issue. It shows no Avergae Layer Time but a strange value below ETA.

Here Estimated Total Print Time is shown.

![Average_Layer_Time_2](https://user-images.githubusercontent.com/60507600/76000668-517ee500-5f04-11ea-9816-1fd38219fd5f.jpg)
![version_2nd_Octoprint-server](https://user-images.githubusercontent.com/60507600/76000679-53e13f00-5f04-11ea-858a-100eeae3d2df.jpg)

**Comment by energiebrand** [comment] 2020-03-05 16:14
Ups...after some more minutes waiting it also shows now a value:
![Average_Layer_Time_3](https://user-images.githubusercontent.com/60507600/76001019-c81be280-5f04-11ea-9290-750a1a60ec8d.jpg)

**Comment by StefanCohen** [comment] 2020-03-06 06:55
The avg layer time is calculated by DLP after the first five layers according to the default setting so it will take some time to be displayed. The setting is configurable in DLP.

**Comment by energiebrand** [comment] 2020-03-06 07:51
ok, understood. But hope you will still work on the problem with the values :-)  If this needes some time until a solution will come maybe it´s better to downgrade to the previous release?

**Comment by StefanCohen** [comment] 2020-03-06 12:26
No worries. I have a fix. It was A typo introduced in 1.11.2.

Fixed in 1.11.4

**Closed by StefanCohen** 2020-03-06 12:26 UTC
Labels: bug

**Comment by energiebrand** [comment] 2020-03-06 15:25
Thanks a lot! Just checked with 1.4.0 on 0.17.0 is working and back to live!
![Avergae_Layer_Time_fixed](https://user-images.githubusercontent.com/60507600/76096902-11cd0180-5fc7-11ea-8eb2-a7f38b86eda9.jpg)
