### ISSUE TITLE
Only installs old version 1.11.4

### ISSUE THREAD

**Issue by chimcen** [StefanCohen/OctoPrint-Dashboard#154] opened 2020-05-16 09:56 UTC
I know that this is a bit long but please take your time and fill in the following information as clearly and detailed as possible. It will shorten the time needed to understand and fix the issue significantly. Please also state versions clearly when applicable. "Latest version" doesn't help much.  

**Describe the bug**
Octoprint just reinstalls only the old v1.11.4

**To Reproduce**
...

**Expected behavior**

**Screenshots**

**Files (please attach the following Files or screenshots when applicable):**
* Octoprint.log
* Browser console log
* gcode file that can be used to reproduce the problem

**OctoPrint server and Plugins:**
 - Platform: [e.g. RPi 3b+, Intel x86]
 - OS and version: [e.g. Raspbian Stretch, Ubuntu 18.10, Windows 10]
 - OctoPrint version: [e.g. OctoPrint 1.3.11]
 - OctoPi version: [e.g. OctoPi 0.16.0]
 - Dashboard version [e.g. Dashboard 1.10.1]
 - DisplayLayerProgress version [e.g. 1.14.0]

**Desktop (please complete the following information):**
 - OS and version: [e.g. Windows 10]
 - Browser and version [e.g. chrome 77.0.3865, safari 12.1.2]

**Additional context**

**Comment by StefanCohen** [comment] 2020-05-16 10:34
Duplicate of #153

**Closed by StefanCohen** 2020-05-16 10:34 UTC
Labels: duplicate
