### ISSUE TITLE
Broken after Update

### ISSUE THREAD

**Issue by LMS0815** [StefanCohen/OctoPrint-Dashboard#79] opened 2019-10-07 11:41 UTC
Not working any longer. 

![Anmerkung 2019-10-07 133956](https://user-images.githubusercontent.com/8235214/66336327-26846b00-e93d-11e9-99c9-3cbd1c1ebb1f.png)

Please DO NOT add all requested features.
I like _dashboard_, unfortunately it is getting overloaded and performance started suffering.

**Comment by StefanCohen** [comment] 2019-10-07 19:13
Same problem as with #77 that was fixed in 1.10.1?

**Comment by solyxius** [comment] 2019-10-07 20:08
Same problem with v1.10.1 on a RPi also ... 

![Dashboard](https://user-images.githubusercontent.com/38299827/66281293-7267ed80-e906-11e9-8db0-00fa5ae29dff.png)

**Comment by StefanCohen** [comment] 2019-10-07 20:23
Interesting. So this is probably unrelated to the fix in 1.10.1 then. Any error messages in octoprint.log or in the browser console?

**Comment by solyxius** [comment] 2019-10-07 21:16
After rolling back to 1.9.0 ... therefore seems to be something to do with 1.10.x?

![image](https://user-images.githubusercontent.com/38299827/66349097-d260a180-e9a3-11e9-8010-b63b462b1ce6.png)

**Comment by StefanCohen** [comment] 2019-10-08 08:55
Hmm. Nothing strange with the versions. What about the browser console log? Any errors in there? 

I'm starting to wonder if this may be related to the introduction of the layer progress gauge in 1.10.0 that binds to the gcode tabs view model. It could be conflict another plugin that somehow disturbs that viewmodel.

Do you still see the problem if you temporarilly disable all other plugins except DisplayLayerProgress, restart Octoprint and reload the browser?

If the problem goes away then, can you please re-enable the plugins again and post the plugin loading section in your octoprint.log from right after the startup. It is the lines following `octoprint.plugin.core - INFO - 18 plugin(s) registered with the system:`

That would allow me to install all your plugins locally and see if that can reproduce the problem.

**Comment by solyxius** [comment] 2019-10-08 10:35
@StefanCohen no joy ... all plugins disabled except -

![image](https://user-images.githubusercontent.com/38299827/66388342-9cf29d00-ea11-11e9-8342-333a8d7c2200.png)

![image](https://user-images.githubusercontent.com/38299827/66388368-aed44000-ea11-11e9-9da0-71fd224090e3.png)

However, there are browser errors related to gcode view model -

![image](https://user-images.githubusercontent.com/38299827/66388402-c6132d80-ea11-11e9-87ee-0498df70d933.png)

**Comment by StefanCohen** [comment] 2019-10-08 11:43
Thanks. It looks like the gcodeViewModel is missing when the Dashboard ViewModel is created. Do you agree @j7126 ?

**Comment by StefanCohen** [comment] 2019-10-08 11:54
Have you possibly disabled the Gcode Visualizer?
![Screenshot 2019-10-08 at 13 48 41](https://user-images.githubusercontent.com/33824565/66393427-cb04bc80-e9d2-11e9-9b6a-80b792e43951.png)

Disabling it causes the same issue on my instance:
![Screenshot 2019-10-08 at 13 52 28](https://user-images.githubusercontent.com/33824565/66393484-ec65a880-e9d2-11e9-91ab-0c66df6f5fd8.png)

The v1.10.0 released introduced a dependency to that tab for the new layer progress gauge.

**Comment by LMS0815** [comment] 2019-10-08 13:27
I never enabled _Gcode Visualizer_ it never was (because it is stuck anyway if the print job is big).
Is there any change to get _Dashboard_ again running without this dependency?

**Comment by StefanCohen** [comment] 2019-10-08 13:33
Ok. Now we know the reason.

 It should be enabled by default (it has at least been in all the versions of OctoPi and OctoPrint I have used so far) so it seems like this is something that has to be manually disabled by users.

I will play a bit to see what happens if we make it optional but I fear that it will break the Dashboard completely.

**Comment by LMS0815** [comment] 2019-10-08 13:33
Just for clarification...
**Dashboard** now depends on
_Gcode Visualizer_ and _Display Layer Progress Plugin_? 
Both needed to create Layer progress gauge?

**Comment by LMS0815** [comment] 2019-10-08 13:36
Yes I manually disabled it because it once crashed and never happend to work again.
Most of my prints are to big for _Gcode Visualizer_  (see description).

**Comment by LMS0815** [comment] 2019-10-08 13:37
> I will play a bit to see what happens if we make it optional but I fear that it will break the Dashboard completely.

Older versions have been working without  _Gcode Visualizer_

**Comment by StefanCohen** [comment] 2019-10-08 13:37
Correct but they are used for different purposes. Gcode Visualizer is used for the layer progress gauge. DisplayLayerProgress is used for layer height, model height, Layer Duration Graph, etc...

There are actually plenty of more dependencies. The complete list of ViewModel dependencies is:

["temperatureViewModel", "printerStateViewModel", "printerProfilesViewModel", "connectionViewModel", "settingsViewModel", "displaylayerprogressViewModel", "controlViewModel", "gcodeViewModel"]

**Comment by StefanCohen** [comment] 2019-10-08 13:39
> Older versions have been working without Gcode Visualizer
Yes. You can always use 1.9 or earlier. These versions didn't have that dependency.

**Comment by LMS0815** [comment] 2019-10-08 13:44
Got it. THX!
I prefer always to us the current version...  (Or not using it, if it is or suitable).
As OctoPrint does not have a Prefered Version switch for plugin updates, the next update would install the current version again.

**Comment by StefanCohen** [comment] 2019-10-08 13:50
No problem. I just tried making the loading of the viewModel optional but that didn't work at all. I will make sure that this requirement is properly described in the readme, releas notes and in the wiki. 

Sorry for the inconvenience. As I said, I wasn't even aware that it is possible to disable the gcode viewer.

@solyxius Does enabling the feature solve your problem?

**Comment by LMS0815** [comment] 2019-10-08 15:03
I can not get gCode viewer to work. - Others might have the same issue...
![Anmerkung 2019-10-08 170310](https://user-images.githubusercontent.com/8235214/66407482-90f4e400-e9ed-11e9-9571-9ca4f5840662.png)

**Comment by StefanCohen** [comment] 2019-10-08 19:20
I'm going to investigate this a bit more to see if we can fail more gracefully but I will close this Issue now that we know the reason and what to expect. 

I will however open a new Feature Request and see what we can do in a future version. The dependency is required for the Layer Progress widget, a feature that was planned from day one. I feel that It may be possible to work around the error and disable the feature for situations like yours. Feel free to provide a PR if you want to help.

**Closed by StefanCohen** 2019-10-08 19:20 UTC
Labels: bug

**Comment by solyxius** [comment] 2019-10-08 20:13
@StefanCohen re-enabling Gcode Visualizer solved the issue, thanks!
