### ISSUE TITLE
Graph window too large. 

### ISSUE THREAD

**Issue by Fribbler** [StefanCohen/OctoPrint-Dashboard#5] opened 2019-09-11 17:32 UTC
**Describe the bug**
The Graph window @ the temperature tab is too large for the layout.

**To Reproduce**
1. Go to 'Temperature window' 
2. Click on 'tab Temperature'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6955078/64720261-52d9d280-d4ca-11e9-9a32-4d38b12c6cb0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version; 76.0.3809.132

**Smartphone (please complete the following information):**
N.a.

**Additional context**
Cyborg theme installed. But with the plugin off I have the same problem.
Microsoft Edge 44.18362.329.0 has the same issue.
If I switch-off the dashboard plugin, the temp. gaph is normal again.

**Comment by StefanCohen** [comment] 2019-09-11 20:12
Hmm. I haven't been able to reproduce this but I'll take a look at it again.

**Comment by Fribbler** [comment] 2019-09-11 21:54
Hi Stefan,

I have tried some more, and now I see that it is a problem in combination with Tempsgraph Plugin (0.3.4) If I disable this plugin the window is OK.

**Comment by Fribbler** [comment] 2019-09-11 21:56
Sorry, Wrong button.

**Comment by StefanCohen** [comment] 2019-09-11 22:03
Good find. I'm away from my dev env right now so I haven't analyzed this but there may be a CSS isssue with clashing Classes or IDs.

**Comment by StefanCohen** [comment] 2019-09-15 17:26
Strange. I have reproduced it. The tempsgraph Plugin sets up an SVG container that is 700*400 px when the dashboard is enabled but it is only 590* 400 when the dashboard is disabled. The standard Temperature tab is not affected. I can't find any css conflicts.
This may be a problem with the tempsgraph Plugin or the Dashboard, but I haven't been able to figure out what triggers the problem.

**Comment by StefanCohen** [comment] 2019-09-20 20:30
closing this issue since I don’t think it is caused by the dashboard after review

**Closed by StefanCohen** 2019-09-20 20:30 UTC
Labels: bug, help wanted
