### ISSUE TITLE
DisplayLayerProgress toggle

### ISSUE THREAD

**Issue by CynanX** [StefanCohen/OctoPrint-Dashboard#151] opened 2020-05-14 06:48 UTC
Hi,

First, love you plugin - thank you for creating it!

Now.. you may have heard that the DisplayLayerPlugin is _apparently_ causing layer shift issues so many have currently disabled it. Whilst you can still use the Dashboard plugin it does pop up a warning each time I go into OctoPrint.

Could you add a control or toggle under it's settings to disable the parts that use this plugin for those that want to run it disabled?

It might be nice to also put in toggles for the other plugin dependencies too.

Thank you!

--Cynan.

**Comment by daveindustries** [comment] 2020-05-14 09:16
Hey Also came here to share the same exact same words as the op about DisplayLayerPlugin.

No need to re write other than to also say Dashboard is an awesome plugin thank you for making it!

D

**Comment by StefanCohen** [comment] 2020-05-14 09:29
Thanks for the feedback.

DLP provides the data for the Fan speed widget, Current/Total layers widget, Current/Total height widget, Average layer duration widget and the Layer duration graph. This is a substantial part of the Dashboard widgets. I can probably add a setting to disable the warning message (at least the popup) but disabling the widgets would be non-trivial as DLP has been a firm required dependency from the start (hence the warning message).

**Comment by daveindustries** [comment] 2020-05-14 10:46
I see, in that case just being able to disable the popup would be an awesome temporary solution.

It's been a few months since disabling DLP so hopefully it will be back working soon.

**Comment by StefanCohen** [comment] 2020-05-14 12:16
Ok.

**Comment by CynanX** [comment] 2020-05-14 12:35
Yeah. Not to bothered about the widgets being hidden, it's the warning annoying! Hopefully the DLP manages to solve the issue soon. Thank you.

**Comment by StefanCohen** [comment] 2020-05-14 14:46
Yeah. I highly doubt that the observed layer shifting is caused by DLP but that's a different story.

**Comment by StefanCohen** [comment] 2020-05-15 22:44
Fixed in 1.12.0

**Closed by StefanCohen** 2020-05-15 22:44 UTC
Labels: enhancement
