### ISSUE TITLE
Wrong total height (eg 2.0000000447mm instead of 2.00mm)

### ISSUE THREAD

**Issue by spanzetta** [StefanCohen/OctoPrint-Dashboard#198] opened 2020-09-03 11:59 UTC
the total height shows a lot of decimals (wrong)

See screenshot below

It happen always

 - Platform: **RPi 3A+**
 - OctoPrint version: **1.4.2**
 - Dashboard version: **1.14**
 - DisplayLayerProgress version: **1.23.2**

 - OS and version: **Windows 10**
 - Browser and version: **Firefox 80**

![report](https://user-images.githubusercontent.com/49818743/92111911-4a6e5c00-eded-11ea-8eb2-4ddfc9add046.jpg)

**Comment by spanzetta** [comment] 2020-09-05 18:48
anyone can confirm the problem?
I also see the same wrong data into JobHistory list..

**Comment by KenLucke** [comment] 2020-09-05 23:20
I have seen this, too (different numbers)

Also, layer % completions of like 132413232%.  Unable to reliably reproduce, but it only seems to happen on large gccode files.

I'll try to grab a screenshot next time I see it.

**Comment by KenLucke** [comment] 2020-09-05 23:34
Another example:

![CR-10 v2 (Yellow) LAN  OctoPrint  - 25% 2020-09-05 16-29-58](https://user-images.githubusercontent.com/57936294/92315049-5c8afe80-ef95-11ea-88fb-b8167bce38aa.jpg)

Actual height of the model in Cura, BTW, is 50.594mm, and it's sitting directlly on the buildplate (no raft or anything else)

**Comment by KenLucke** [comment] 2020-09-05 23:46
![CR-10v2 (Blue) LAN  OctoPrint  - 31% 2020-09-05 16-45-21](https://user-images.githubusercontent.com/57936294/92315186-50a03c00-ef97-11ea-9a2d-114a2a38b980.jpg)

**Comment by AngusCox** [comment] 2020-09-06 16:44
Same issue here!

<img width="908" alt="Hight error" src="https://user-images.githubusercontent.com/54340236/92330669-f959a480-f046-11ea-8a14-d9843f2dd341.png">

**Comment by spanzetta** [comment] 2020-09-06 17:49
Thanks to all..

I wonder if the author (@StefanCohen) is reading these post..

**Comment by KenLucke** [comment] 2020-09-06 19:20
> I wonder if the author (@StefanCohen) is reading these post..

You know, most of these authors a) have other lives, b) don't make money doing this and have to feed themselves [and possibly others] in those other lives, and c) we don't know what they are going through in those other lives.

Give 'em a break.  It's only been 3 days since you opened this, and it's certainly a non-critical issue in a non-critical (albiet very useful) plugin.

**Comment by KenLucke** [comment] 2020-09-06 19:24
This is also a duplicate of #193 , for which there is a patch [#195] (I am just about to apply it, but it was confirmed that it worked by others)

**Comment by spanzetta** [comment] 2020-09-07 06:47
Thanks @KenLucke .. I didn't want to push (it was just a question) .. and I understand what you mean..

**Comment by StefanCohen** [comment] 2020-09-07 13:31
Thanks for the feedback. The Dashboard gets the current height from the DLP plugin. It looks like a recent DLP release may have increased the precision a bit and my rounding needs to be fixed as per the PR from Olli. I'll take a look at that and will close this ticket as a duplicate.

**Closed by StefanCohen** 2020-09-07 13:31 UTC
Labels: bug, duplicate

**Comment by spanzetta** [comment] 2020-09-07 13:49
I did the suggested manual fix and it works!
Thanks

**Comment by AngusCox** [comment] 2020-09-07 14:32
> I did the suggested manual fix and it works!
> Thanks

Same for me!
Thanks you all.
