### ISSUE TITLE
Broken update on PC/x86

### ISSUE THREAD

**Issue by Loloke** [StefanCohen/OctoPrint-Dashboard#77] opened 2019-10-06 21:23 UTC
Update is broken on non-RPi installation:

**To Reproduce**
Simply click on update

**Expected behavior**
Update without errors :)

**Desktop (please complete the following information):**
Windows 10, Chrome v77, but i dont think it matters

**System**
Ubuntu 18.04.3, x86-64

**Additional context**
[Octoprint-Dashboard_update_error.txt](https://github.com/StefanCohen/OctoPrint-Dashboard/files/3694873/Octoprint-Dashboard_update_error.txt)

**Comment by StefanCohen** [comment] 2019-10-06 21:35
That is caused by the DHT library needed for the sensor input added in v1.10.0. 
I need to check if it is possible to make it conditional in the installer somehow. Either that or three other options:

- Force RPi users to install it manually.
- Stop supporting non-RPi installations.
- Remove the feature.

**Comment by j7126** [comment] 2019-10-06 22:52
I have a fix for this

**Comment by j7126** [comment] 2019-10-06 23:11
fixed PR #78

**Comment by solyxius** [comment] 2019-10-07 02:29
Something amiss on a RPi also ...
![Dashboard](https://user-images.githubusercontent.com/38299827/66281293-7267ed80-e906-11e9-8db0-00fa5ae29dff.png)
![Console](https://user-images.githubusercontent.com/38299827/66281295-74ca4780-e906-11e9-8f13-474accd3b152.png)

**Comment by StefanCohen** [comment] 2019-10-07 03:45
Modified commit by @j7126 and added check to see if the setup is running on an RPi by trying to load the RPI.GPIO module. I have verified on both an RPi and in an Ubuntu LXC container and both worked. Fixed in v1.10.1 Please report back with a verification if it works or not.

**Comment by overload08** [comment] 2019-10-07 08:12
Hi !
Doesn't work on PC :

```
Oct  7 10:08:32 octo octoprint[16819]: 2019-10-07 10:08:32,792 - octoprint.plugin.core - ERROR - Error loading plugin dashboard
Oct  7 10:08:32 octo octoprint[16819]: Traceback (most recent call last):
Oct  7 10:08:32 octo octoprint[16819]:   File "/home/sysadmin/OctoPrint/venv/local/lib/python2.7/site-packages/OctoPrint-1.3.11-py2.7.egg/octoprint/plugin/core.py", line 863, in _import_plugin
Oct  7 10:08:32 octo octoprint[16819]:     instance = imp.load_module(module_name, f, filename, description)
Oct  7 10:08:32 octo octoprint[16819]:   File "/home/sysadmin/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_dashboard/__init__.py", line 17, in <module>
Oct  7 10:08:32 octo octoprint[16819]:     import Adafruit_DHT
Oct  7 10:08:32 octo octoprint[16819]: ImportError: No module named Adafruit_DHT
```

**Comment by StefanCohen** [comment] 2019-10-07 08:55
@overload08 can you confirm that you tried with v1.10.1 and not v1.10.0?

**Comment by overload08** [comment] 2019-10-07 08:56
Yeah, I installed Adafruit_DHT and it was ok

**Comment by StefanCohen** [comment] 2019-10-07 08:58
Allright. I need to find a Windows machine and try it myself.

**Comment by j7126** [comment] 2019-10-07 09:06
I tested my PR on Windows and on a pi and it worked fine on both.

**Comment by overload08** [comment] 2019-10-07 09:08
Just a precision, i've tested on linux...

**Comment by j7126** [comment] 2019-10-07 09:14
I have just tested v1.10.1 on windows and it is working fine with no problems, it seems that this will require some further investigation.

**Comment by j7126** [comment] 2019-10-07 09:23
@StefanCohen 

The following screenshot is from an octoprint instance running on windows: 
![image](https://user-images.githubusercontent.com/35882868/66299572-21242200-e937-11e9-85db-1942d31efd3e.png)

And the following screenshot if form an octoprint instance running on octopi on raspberry pi:
![image](https://user-images.githubusercontent.com/35882868/66299639-3f8a1d80-e937-11e9-8faf-13c353465f32.png)

It is not properly detecting the new version of the plugin that is available. When the update button is pressed it simply does nothing. I had to uninstall and re-install the plugin to get it to work. 
I am not yet sure if it is related to this but it is interesting.

**Comment by solyxius** [comment] 2019-10-07 10:07
On RPi I had to go to Advanced Options in the software updates and bypass cache to retrieve the latest version version

**Comment by Loloke** [comment] 2019-10-07 10:35
v1.10.1 works fine, thanks!

**Comment by StefanCohen** [comment] 2019-10-07 11:08
@j7126 The cache thing is a mystery. Have you tried what @solyxius describes? That usually works for me when this happens to me. I have noticed that it only happens for me when going from a .0 to a .1. 
Anyway. This seems to be working now. Thanks for the help!

**Closed by StefanCohen** 2019-10-07 11:08 UTC
Labels: bug
