### ISSUE TITLE
Feature Request - Pause & Cancel

### ISSUE THREAD

**Issue by retikulumx** [StefanCohen/OctoPrint-Dashboard#87] opened 2019-10-08 21:35 UTC
It would be cool, if you could implement the "Pause" and "Cancel" button. I'm using an old tablet as display for my printer. But sometimes I have to interrupt the print. 
Thanks :-)

**Comment by StefanCohen** [comment] 2019-10-08 21:40
So I guess you are using it in fullscreen mode on the tablet?

I have already added support for pause/cancel, but it is only available via a context menu by clicking on the file name. I guess that is a no-go on a tablet...

**Comment by retikulumx** [comment] 2019-10-09 11:03
Hi.
Yes, exactly. I'm using it in full screen mode.
Would be very comfortable to place 2 buttons directly to the screen.
But maybe the "cancel" button with a "are you really sure" prompt. If that's not possible, the _pause_ button should be enough I guess.

**Comment by StefanCohen** [comment] 2019-10-12 08:04
WIP:

![Screenshot 2019-10-12 at 10 01 31](https://user-images.githubusercontent.com/33824565/66697592-50d87e80-ecd7-11e9-8ac6-a94047dc85a3.png)

@j7126 There is a slight problem with the cancel confirmation modal dialog. It is not displayed on top of the fullscreen element so it is hidden until I exit fullscreen. Do you have any ideas how to solve that? I guess it has to be done from js but I haven't found a way yet.

**Comment by j7126** [comment] 2019-10-13 00:50
@StefanCohen the reason that the confirmation dialog is hidden in fullscreen is because since you are just duplicating the default buttons and confirmation dialog which is part of octoprint, this dialog is outside of the dashboard element. Because only the dashboard element is what is fullscreen that is why this is happening.

I will work on a solution.

**Comment by j7126** [comment] 2019-10-13 01:20
@StefanCohen fixed in #94

**Comment by StefanCohen** [comment] 2019-10-13 08:14
Confirmed fixed in #94. Thanks again!

**Comment by StefanCohen** [comment] 2019-10-13 20:53
Fixed in 1.11.0

**Closed by StefanCohen** 2019-10-13 20:53 UTC
Labels: enhancement
