### ISSUE TITLE
Bad formatting in Dashboard 1.11.0 plugin settings 

### ISSUE THREAD

**Issue by ochm** [StefanCohen/OctoPrint-Dashboard#98] opened 2019-10-14 15:54 UTC
**Describe the bug**
Bad formatting of input boxes and texts

**To Reproduce**
Open dashboard plugin settings

**Expected behavior**
Proper formatting

**Screenshots**
![image](https://user-images.githubusercontent.com/47606742/66764864-ff80e880-eeaa-11e9-9b99-782cbed96ffa.png)

![image](https://user-images.githubusercontent.com/47606742/66765090-73bb8c00-eeab-11e9-909b-c0984691911d.png)

Platform: RPi 4
OctoPrint version : 1.3.11
OctoPi version    : 0.17.0

**Desktop (please complete the following information):**
OS and version: W8.1 64bit
Chrome, Firefox

**Comment by StefanCohen** [comment] 2019-10-14 16:17
Interesting. It doesn’t render like that for me in any browser.

**Comment by StefanCohen** [comment] 2019-10-14 20:47
This is how it looks here in Safari, Chrome and Firefox:

![Screenshot 2019-10-14 at 22 26 54](https://user-images.githubusercontent.com/33824565/66781745-64046d80-eed4-11e9-9f6e-0bcf036dccd8.png)

I have regardless added some vertical space in the settings dialog and pushed a change (no release yet). Please try it by installing via the plugin manager directly from this URL: https://github.com/StefanCohen/OctoPrint-Dashboard/archive/master.zip

**Comment by ochm** [comment] 2019-10-15 07:45
I probably know where is problem. My white theme is default Octoprint theme. Here is bad formatting. Your dark theme is from Themeify plugin (i guess), and yes when i turn on this plugin, the rendering is OK. Only the up and down buttons are very, very small.
![image](https://user-images.githubusercontent.com/47606742/66810918-77ddbd00-ef30-11e9-9443-7ccc7ca408f2.png)

**Comment by StefanCohen** [comment] 2019-10-15 07:54
This is my dashboard in Chrome without Themeify installed:

![Screenshot 2019-10-15 at 09 48 54](https://user-images.githubusercontent.com/33824565/66811370-3ef21800-ef31-11e9-9645-930d135535c8.png)

This is very strange. What other plugins are you using?

**Comment by StefanCohen** [comment] 2019-10-15 21:00
I guess one method to pinpoint this would be to disable them all except the dashboard to see if it clears the issue and then enable them one by one until it happens again. That would take a while... I will have to postpone that a bit since I'm currently focusing on the OctoPrint 1.4 support.

**Comment by ochm** [comment] 2019-10-16 23:48
Hi, 

I disabled all available plugins, and the problem disapear. 
Then i sequentialy enabled and restarted Octoprint after each enabled plugin and the problem doesn't come back, but only in Chrome. 
In Firefox ESR is the rendering still bad in default theme, even if the browser cache is cleared, 
with Themeify everything looks well. 

I can live with this. :) 


​​-- 
Martin Och 
Mikrotik: MTCNA, MTCWE, MTCTCE 
Veeam: VMTSP, VMSP 
VMware: VCP6-DCV

**Comment by StefanCohen** [comment] 2019-10-17 12:28
Ok. I can't reproduce it at all so I think we have to close the issue. At least for now. Please re-open if you find any more info.

**Comment by ochm** [comment] 2019-10-21 17:31
I made short investigation, in Chrome and Firefox ESR to see how the settings of Dashboard are formated..

Without Themeify plugin:
Chrome (latest) OK
Firefox ESR (latest) NOK

With Themeify plugin:
Chrome (latest):
Discorded OK
Material UI Light OK
Cyborg NOK
Discoranged OK
Dyl OK
Nighttime OK

Firefox ESR (latest):
Discorded OK
Material UI Light NOK
Cyborg NOK
Discoranged OK
Dyl OK
Nighttime OK

**Comment by StefanCohen** [comment] 2019-10-21 20:10
Thanks!

I can reproduce the problem now and will try to come up with a fix.

**Comment by StefanCohen** [comment] 2019-10-21 20:31
Ok. This is probably a bug in some of the themeify themes but I have managed to work around it in FF. These are my results:



FF, Material UI Light:
![Screenshot 2019-10-21 at 22 24 10](https://user-images.githubusercontent.com/33824565/67240343-8dcc1000-f451-11e9-992d-84288607ff84.png)

FF, Cyborg:
![Screenshot 2019-10-21 at 22 25 01](https://user-images.githubusercontent.com/33824565/67240389-a89e8480-f451-11e9-96f3-90f459b8343d.png)

Chrome still exhibits the same problem after the fix so I think you will need to address this with the Themeify plugin author to get a resolution.

**Closed** 2020-01-30 13:54 UTC
Labels: bug
